// monday.com Work OS — אפיון v2, שלב 1 (19 לוחות).
// מקור מחייב: נספח 19 באפיון. מזהי עמודות קבועים (אותיות קטנות וקו תחתון בלבד, עד 20 תווים)
// כדי שנוסחאות ותרחישי Make יפנו אליהם בשם יציב ולא במזהה אקראי.
//
// סוגי עמודות: text, long_text, numbers, date, people, phone, email, link, file, checkbox,
// rating, timeline, location, auto_number, creation_log, status, dropdown,
// relation (board_relation), mirror, formula.

const VERIFIED_CHAPTERS = {
  '00': '00 מוקדמות',
  '01': '01 עבודות עפר',
  '02': '02 בטון יצוק באתר',
  '04': '04 עבודות בנייה',
  '05': '05 עבודות איטום',
  '06': '06 נגרות אומן ומסגרות',
  '07': '07 מתקני תברואה',
  '08': '08 מתקני חשמל',
  '09': '09 עבודות טיח',
  '10': '10 ריצוף וחיפוי',
  '11': '11 עבודות צבע',
  '12': '12 עבודות אלומיניום',
  '14': '14 עבודות אבן',
};
// 15, 18, 19, 22, 34 — "לא מאומת" באפיון; נשארים כמספר בלבד עד אימות מול המפרט הכללי.
const chapter = (n) => VERIFIED_CHAPTERS[n] ?? n;

// TODAY() ב-monday כולל שעה, ולכן DAYS מולו מחזיר שבר. FORMAT_DATE מנרמל לתאריך בלבד.
const T = 'FORMAT_DATE(TODAY(),"YYYY-MM-DD")';

const TASK_COLUMNS = [
  { id: 'rec_id', title: 'מזהה', type: 'auto_number', prefix: 'T-' },
  { id: 'task_type', title: 'סוג', type: 'status', labels: ['חד-פעמית', 'שגרה חוזרת', 'מפגישה', 'בקשה מהצוות', 'מעקב מול גורם חיצוני'] },
  { id: 'domain', title: 'תחום', type: 'dropdown', labels: ['משרד', 'כספים', 'ביטוח', 'רכבים', 'משאבי אנוש', 'מחשוב', 'ציות', 'פרויקט'] },
  { id: 'owner', title: 'אחראי', type: 'people' },
  { id: 'requester', title: 'מבקש', type: 'people' },
  { id: 'status', title: 'סטטוס', type: 'status', labels: ['חדש', 'בטיפול', 'ממתין לגורם חיצוני', 'ממתין להחלטה', 'הושלם', 'בוטל'] },
  { id: 'waiting_for', title: 'ממתין ל...', type: 'text' },
  { id: 'followup', title: 'תאריך מעקב', type: 'date' },
  { id: 'due', title: 'תאריך יעד', type: 'date' },
  { id: 'priority', title: 'עדיפות', type: 'status', labels: ['דחוף', 'גבוה', 'רגיל', 'נמוך'] },
  { id: 'meeting_type', title: 'סוג פגישה', type: 'dropdown', labels: ['תפעול שבועי', 'כספים חודשי', 'פרויקט', 'הנהלה'] },
  { id: 'template', title: 'תבנית', type: 'status', labels: ['ללא', 'קליטת עובד', 'פתיחת שנה', 'סגירת פרויקט'],
    description: 'מפעיל את A23 — יצירת תת-פריטים לפי תבנית' },
  { id: 'decision_helper', title: 'תאריך עזר החלטה', type: 'date', description: 'A22 — נכתב באוטומציה כשהסטטוס עובר לממתין להחלטה' },
  { id: 'project', title: 'פרויקט', type: 'relation', target: 'projects' },
  { id: 'created', title: 'יומן יצירה', type: 'creation_log' },
  { id: 'int_key', title: 'מפתח אינטגרציה', type: 'text' },
];

export const workspaces = [
  { key: 'w00', name: '00 נתוני יסוד' },
  { key: 'w10', name: '10 מכירות' },
  { key: 'w20', name: '20 פרויקטים ושטח' },
  { key: 'w30', name: '30 רכש וכספים' },
  { key: 'w50', name: '50 הנהלה' },
];

export const boards = [
  // ───────────────────────────── 00 נתוני יסוד ─────────────────────────────
  {
    key: 'clients', ws: 'w00', name: 'לקוחות וחברות', kind: 'public', nameTitle: 'שם חברה',
    description: 'כל ישות עסקית: לקוח, אדריכל/מעצב, מפקח, שותף, יועץ. בעלים: מנהלת המשרד. (אפיון §5.1)',
    groups: ['לקוחות פעילים', 'פוטנציאליים', 'אדריכלים ומעצבים', 'אחרים'],
    columns: [
      { id: 'rec_id', title: 'מזהה', type: 'auto_number', prefix: 'C-' },
      { id: 'company_type', title: 'סוג חברה', type: 'status', labels: ['לקוח', 'אדריכל/מעצב', 'מפקח', 'שותף', 'יועץ'] },
      { id: 'tax_id', title: 'ח״פ', type: 'text' },
      { id: 'city', title: 'עיר', type: 'text' },
      { id: 'phone', title: 'טלפון', type: 'phone' },
      { id: 'email', title: 'דוא״ל', type: 'email' },
      { id: 'morning_id', title: 'מזהה Morning', type: 'text' },
      { id: 'referrals', title: 'מספר הפניות', type: 'mirror', relation: 'leads', from: 'leads', column: 'lead_type', deferred: true,
        description: 'סיכום סוגי הלידים המקושרים (ספירת "הפניה"). נוסחה לא יכולה לספור פריטים מקושרים לפי סוג.' },
      { id: 'created', title: 'יומן יצירה', type: 'creation_log' },
      { id: 'int_key', title: 'מפתח אינטגרציה', type: 'text' },
    ],
  },
  {
    key: 'contacts', ws: 'w00', name: 'אנשי קשר', kind: 'public', nameTitle: 'שם',
    description: 'אדם, מקושר לחברה. טלפון בפורמט E.164 עבור וואטסאפ. (אפיון §5.2)',
    groups: ['פעילים', 'ארכיון'],
    columns: [
      { id: 'rec_id', title: 'מזהה', type: 'auto_number', prefix: 'CT-' },
      { id: 'company', title: 'חברה', type: 'relation', target: 'clients', single: true, reflect: 'אנשי קשר', reflectId: 'contacts' },
      { id: 'role', title: 'תפקיד', type: 'text' },
      { id: 'phone', title: 'טלפון', type: 'phone', description: 'E.164, לדוגמה ‎+972501234567' },
      { id: 'email', title: 'דוא״ל', type: 'email' },
      { id: 'wa_consent', title: 'הסכמה לוואטסאפ', type: 'checkbox' },
      { id: 'consent_date', title: 'תאריך הסכמה', type: 'date' },
      { id: 'created', title: 'יומן יצירה', type: 'creation_log' },
      { id: 'int_key', title: 'מפתח אינטגרציה', type: 'text' },
    ],
  },
  {
    key: 'vendors', ws: 'w00', name: 'ספקים וקבלני משנה', kind: 'public', nameTitle: 'שם ספק',
    description: 'ספק או קבלן משנה. המזהה V-0001 זהה לכרטיס במערכת החשבונות. סטטוס ציות נכתב ע״י M07. (אפיון §5.3)',
    groups: ['קבלני משנה', 'ספקי חומרים', 'קבלני כוח אדם', 'שירותים'],
    columns: [
      { id: 'rec_id', title: 'מזהה', type: 'auto_number', prefix: 'V-' },
      { id: 'vendor_code', title: 'מזהה ספק', type: 'text', description: 'V-0001 — זהה לכרטיס הספק במערכת החשבונות' },
      { id: 'tax_id', title: 'ח״פ', type: 'text' },
      { id: 'vendor_type', title: 'סוג ספק', type: 'status', labels: ['קבלן משנה', 'ספק חומרים', 'קבלן כוח אדם', 'שירותים'] },
      { id: 'trade', title: 'מקצוע', type: 'dropdown', labels: ['04', '05', '06', '07', '08', '09', '10', '11', '12', '22'].map(chapter) },
      { id: 'phone', title: 'טלפון', type: 'phone' },
      { id: 'email', title: 'דוא״ל', type: 'email' },
      { id: 'insurance_exp', title: 'תוקף ביטוח', type: 'date' },
      { id: 'wht_exp', title: 'תוקף ניכוי במקור', type: 'date' },
      { id: 'books_exp', title: 'תוקף ניהול ספרים', type: 'date' },
      { id: 'manpower_exp', title: 'תוקף רישיון כוח אדם', type: 'date' },
      { id: 'days_to_expiry', title: 'ימים לתוקף הקרוב', type: 'formula',
        formula: `MIN(DAYS({insurance_exp},${T}),DAYS({wht_exp},${T}),DAYS({books_exp},${T}),IF({vendor_type}="קבלן כוח אדם",DAYS({manpower_exp},${T}),9999))` },
      { id: 'compliance', title: 'סטטוס ציות', type: 'status', labels: ['תקין', 'פג בעוד 30', 'פג בעוד 7', 'פג תוקף', 'חסר'],
        description: 'נכתב ע״י M07 (לא נוסחה — נוסחאות אינן אמינות כתנאי לאוטומציה)' },
      { id: 'pay_block', title: 'חסימת תשלום', type: 'checkbox', description: 'נכתב ע״י M07' },
      { id: 'framework_exp', title: 'תוקף הסכם מסגרת', type: 'date' },
      { id: 'pricelist', title: 'קישור מחירון', type: 'link' },
      { id: 'bank_status', title: 'פרטי בנק', type: 'status', labels: ['מאומת', 'שונה', 'ממתין לאימות'],
        description: 'הגבלת צפייה לסמנכ״ל — להגדיר ידנית (הרשאות עמודה)' },
      { id: 'bank_callback', title: 'אימות טלפוני חוזר', type: 'status', labels: ['לא בוצע', 'בוצע'] },
      { id: 'last_rating', title: 'דירוג אחרון', type: 'rating' },
      { id: 'int_status', title: 'סטטוס אינטגרציה', type: 'status', labels: ['תקין', 'שגיאת אינטגרציה'] },
      { id: 'created', title: 'יומן יצירה', type: 'creation_log' },
      { id: 'int_key', title: 'מפתח אינטגרציה', type: 'text' },
    ],
  },

  // ───────────────────────────── 10 מכירות ─────────────────────────────
  {
    key: 'leads', ws: 'w10', name: 'לידים והזדמנויות', kind: 'public', nameTitle: 'ליד / הזדמנות',
    description: 'ליד, מכרז או הזדמנות (L26-0001). כולל Go/No-Go, הצעה נוכחית ומסלול אישור. זכייה מפעילה את M02. (אפיון §5.4)',
    groups: ['לידים חדשים', 'בבירור וסיור', 'תמחור והצעה', 'משא ומתן', 'זכייה וחוזה', 'הפסד / לא מתאים'],
    columns: [
      { id: 'rec_id', title: 'מזהה', type: 'auto_number', prefix: 'L-' },
      { id: 'lead_type', title: 'סוג', type: 'status', labels: ['ליד', 'מכרז', 'הפניה'] },
      { id: 'source', title: 'מקור', type: 'status', labels: ['אתר', 'Meta', 'Google Ads', 'LinkedIn', 'הפניה', 'טלפון'] },
      { id: 'stage', title: 'שלב עסקה', type: 'status',
        labels: ['ליד חדש', 'שיחת היכרות', 'סיור באתר', 'Go/No-Go', 'בתמחור', 'הצעה הוגשה', 'משא ומתן', 'זכייה', 'הפסד', 'חוזה נחתם', 'לא מתאים'] },
      { id: 'company', title: 'חברה', type: 'relation', target: 'clients', single: true, reflect: 'לידים', reflectId: 'leads' },
      { id: 'contact', title: 'איש קשר', type: 'relation', target: 'contacts' },
      { id: 'owner', title: 'אחראי', type: 'people' },
      { id: 'tender_due', title: 'תאריך הגשת מכרז', type: 'date' },
      { id: 'tender_q', title: 'מועד שאלות מכרז', type: 'date' },
      { id: 's_niche', title: 'נישה', type: 'rating' },
      { id: 's_class', title: 'סיווג', type: 'rating' },
      { id: 's_credit', title: 'אשראי לקוח', type: 'rating' },
      { id: 's_designer', title: 'מתכנן/מפקח', type: 'rating' },
      { id: 's_schedule', title: 'לוז ריאלי', type: 'rating' },
      { id: 's_competition', title: 'תחרות', type: 'rating' },
      { id: 's_repeat', title: 'פוטנציאל חוזר', type: 'rating' },
      { id: 's_team', title: 'זמינות צוות', type: 'rating' },
      { id: 'score', title: 'ציון', type: 'formula',
        formula: 'ROUND(({s_niche}+{s_class}+{s_credit}+{s_designer}+{s_schedule}+{s_competition}+{s_repeat}+{s_team})/8,2)' },
      { id: 'decision', title: 'החלטה', type: 'formula',
        description: 'ריק עד שמדרגים. סיווג או אשראי ≤ 2 = No-Go חובה',
        formula: 'IF(({s_niche}+{s_class}+{s_credit}+{s_designer}+{s_schedule}+{s_competition}+{s_repeat}+{s_team})=0,"",IF(OR({s_class}<=2,{s_credit}<=2),"No-Go חובה",IF({score}>=3.5,"Go","No-Go")))' },
      { id: 'expected_value', title: 'ערך צפוי', type: 'numbers' },
      { id: 'probability', title: 'הסתברות', type: 'numbers', description: 'באחוזים (0-100)' },
      { id: 'weighted', title: 'ערך משוקלל', type: 'formula', formula: 'ROUND({expected_value}*{probability}/100,0)' },
      { id: 'price', title: 'מחיר', type: 'numbers' },
      { id: 'margin', title: 'רווחיות %', type: 'numbers' },
      { id: 'min_margin', title: 'רווחיות מינימלית', type: 'numbers' },
      { id: 'discount', title: 'הנחה %', type: 'numbers' },
      { id: 'approval_tier', title: 'דרג אישור הצעה', type: 'formula',
        formula: 'IF(OR({price}>1500000,{margin}<{min_margin},{discount}>3),"מנכ״ל","סמנכ״ל")' },
      { id: 'approval', title: 'מסלול אישור', type: 'status', labels: ['לא הוגש', 'ממתין סמנכ״ל', 'ממתין מנכ״ל', 'אושר', 'נדחה', 'דרוש תיקון'],
        description: 'נכתב ע״י M03' },
      { id: 'quote_date', title: 'תאריך הגשת הצעה', type: 'date' },
      { id: 'days_to_quote', title: 'ימים ליד-הצעה', type: 'formula',
        formula: 'IF({quote_date}="","",ROUND(DAYS({quote_date},{created}),0))' },
      { id: 'quote_link', title: 'קישור גרסאות הצעה', type: 'link', description: 'תיקיית Drive עם Q26-0031-R2 וכו׳' },
      { id: 'win_loss', title: 'סיבת זכייה/הפסד', type: 'dropdown', labels: ['מחיר', 'לוז', 'ניסיון', 'קשר', 'איכות', 'אחר'] },
      { id: 'competitor_price', title: 'מחיר מתחרה', type: 'numbers' },
      { id: 'project', title: 'פרויקט', type: 'relation', target: 'projects', single: true, reflect: 'ליד מקור', reflectId: 'lead',
        description: 'נכתב ע״י M02 בזכייה' },
      { id: 'int_status', title: 'סטטוס אינטגרציה', type: 'status', labels: ['תקין', 'שגיאת אינטגרציה'] },
      { id: 'created', title: 'יומן יצירה', type: 'creation_log' },
      { id: 'int_key', title: 'מפתח אינטגרציה', type: 'text' },
    ],
  },

  // ───────────────────────────── 20 פרויקטים ושטח ─────────────────────────────
  {
    key: 'projects', ws: 'w20', name: 'תיק פרויקטים', kind: 'public', nameTitle: 'שם פרויקט',
    description: 'פרויקט P26-014 (הקוד נקבע ע״י M02). השורה הכספית החודשית נכתבת ע״י M10 — "נכון לסגירת חודש". (אפיון §5.5)',
    groups: ['הקמה', 'התנעה', 'ביצוע', 'מסירה', 'אחריות', 'סגור', 'מוקפא'],
    columns: [
      { id: 'rec_id', title: 'מזהה', type: 'auto_number', prefix: 'P-' },
      { id: 'project_code', title: 'קוד פרויקט', type: 'text', description: 'P26-014 — נקבע ע״י M02' },
      { id: 'phase', title: 'שלב', type: 'status', labels: ['הקמה', 'התנעה', 'ביצוע', 'מסירה', 'אחריות', 'סגור', 'מוקפא'] },
      { id: 'client', title: 'לקוח', type: 'relation', target: 'clients', single: true, reflect: 'פרויקטים', reflectId: 'projects' },
      { id: 'pm', title: 'מנהל פרויקט', type: 'people' },
      { id: 'site_mgr', title: 'מנהל ביצוע', type: 'people' },
      { id: 'timeline', title: 'ציר זמן', type: 'timeline' },
      { id: 'address', title: 'כתובת', type: 'location' },
      { id: 'contract_value', title: 'ערך חוזה', type: 'numbers', description: 'מוגבל: מנכ״ל, סמנכ״ל, בקר, מנהל פרויקט' },
      { id: 'approved_changes', title: 'שינויים מאושרים', type: 'numbers', description: 'נכתב ע״י M09a' },
      { id: 'actual_cost', title: 'עלות בפועל', type: 'numbers', description: 'M10 · מוגבל: מנכ״ל, סמנכ״ל, בקר' },
      { id: 'eac', title: 'צפי עלות לסיום', type: 'numbers', description: 'M10 · מוגבל: מנכ״ל, סמנכ״ל, בקר' },
      { id: 'forecast_margin', title: 'רווחיות צפויה %', type: 'numbers', description: 'M10 · מוגבל: מנכ״ל, סמנכ״ל, בקר' },
      { id: 'earned_revenue', title: 'הכנסה שהורווחה', type: 'numbers', description: 'M10 · מוגבל: מנכ״ל, סמנכ״ל, בקר' },
      { id: 'over_under', title: 'חיוב יתר/חסר', type: 'numbers', description: 'M10 · מוגבל: מנכ״ל, סמנכ״ל, בקר' },
      { id: 'as_of_close', title: 'נכון לסגירת חודש', type: 'date', description: 'תאריך הסגירה שאליו מתייחסת השורה הכספית (M10)' },
      { id: 'fin_freshness', title: 'עדכניות נתון כספי', type: 'formula',
        formula: `IF({as_of_close}="","",IF(DAYS(${T},{as_of_close})>45,"נתון כספי ישן",""))` },
      { id: 'missing_journals', title: 'ימי יומן חסרים', type: 'numbers', description: 'נכתב ע״י M11b' },
      { id: 'unapproved_changes', title: 'שינויים ללא אישור', type: 'numbers' },
      { id: 'open_defects', title: 'ליקויים פתוחים', type: 'numbers' },
      { id: 'drive_folder', title: 'תיקיית Drive', type: 'link', description: 'נכתב ע״י M02' },
      { id: 'on_time', title: 'מסירה בזמן', type: 'status', labels: ['כן', 'לא', 'טרם'] },
      { id: 'nps', title: 'NPS', type: 'numbers' },
      { id: 'created', title: 'יומן יצירה', type: 'creation_log' },
      { id: 'int_key', title: 'מפתח אינטגרציה', type: 'text' },
    ],
  },
  {
    key: 'changes', ws: 'w20', name: 'שינויים וחריגים', kind: 'public', nameTitle: 'תיאור שינוי',
    description: 'שינוי מול לקוח או דרישת קבלן משנה (CO-26-014-03). A04: בוצע ללא אישור. A05: הסדרה בכתב תוך 7 ימים. (אפיון §5.6)',
    groups: ['פתוחים', 'אושרו', 'נסגרו'],
    columns: [
      { id: 'rec_id', title: 'מזהה', type: 'auto_number', prefix: 'CO-' },
      { id: 'change_code', title: 'מזהה שינוי', type: 'text', description: 'CO-26-014-03' },
      { id: 'change_type', title: 'סוג', type: 'status', labels: ['שינוי ללקוח', 'דרישת קבלן משנה'] },
      { id: 'status', title: 'סטטוס', type: 'status', labels: ['פוטנציאלי', 'בתמחור', 'הוגש', 'אושר', 'נדחה', 'חויב', 'בוצע ללא אישור'] },
      { id: 'owner', title: 'אחראי', type: 'people', description: 'מנהל הפרויקט — יעד ההתראות של A04/A05' },
      { id: 'identified', title: 'תאריך זיהוי', type: 'date' },
      { id: 'submitted', title: 'תאריך הגשה', type: 'date' },
      { id: 'days_to_submit', title: 'ימים להגשה', type: 'formula',
        formula: `IF({identified}="","",IF({submitted}="",DAYS(${T},{identified}),DAYS({submitted},{identified})))` },
      { id: 'pricing_method', title: 'שיטת תמחור', type: 'dropdown', labels: ['מחירון חוזה', 'דקל', 'ניתוח מחיר', 'יומית'] },
      { id: 'amount', title: 'סכום', type: 'numbers' },
      { id: 'cost', title: 'עלות', type: 'numbers' },
      { id: 'schedule_impact', title: 'השפעה על לוז (ימים)', type: 'numbers' },
      { id: 'sub_tier', title: 'דרג אישור דרישת קבלן משנה', type: 'formula',
        formula: 'IF({change_type}="דרישת קבלן משנה",IF({amount}<=10000,"מנהל פרויקט",IF({amount}<=50000,"סמנכ״ל","מנכ״ל")),"")' },
      { id: 'executed', title: 'בוצע', type: 'checkbox' },
      { id: 'approval_file', title: 'קובץ אישור בכתב', type: 'file' },
      { id: 'urgent_date', title: 'תאריך אישור דחוף', type: 'date' },
      { id: 'urgent_link', title: 'אישור דחוף בוואטסאפ/דוא״ל', type: 'link' },
      { id: 'written_due', title: 'מועד הסדרה בכתב', type: 'formula',
        formula: 'IF({urgent_date}="","",FORMAT_DATE(ADD_DAYS({urgent_date},7),"YYYY-MM-DD"))' },
      { id: 'budget_line', title: 'שורת תקציב', type: 'relation', target: 'budget', single: true, reflect: 'שינויים', reflectId: 'changes' },
      { id: 'billed_in', title: 'חויב בחשבון', type: 'relation', target: 'billing', single: true, reflect: 'שינויים שחויבו', reflectId: 'changes' },
      { id: 'project', title: 'פרויקט', type: 'relation', target: 'projects', single: true },
      { id: 'created', title: 'יומן יצירה', type: 'creation_log' },
      { id: 'int_key', title: 'מפתח אינטגרציה', type: 'text' },
    ],
  },
  {
    key: 'journals', ws: 'w20', name: 'יומני עבודה', kind: 'public', nameTitle: 'יומן',
    description: 'יומן יומי לפרויקט (נקלט מטופס). תת-פריטים: כוח אדם לפי קבלן משנה. M11b בודק יומן חסר ב-17:00. שמירה לשנה. (אפיון §5.7)',
    groups: ['החודש', 'ארכיון'],
    columns: [
      { id: 'rec_id', title: 'מזהה', type: 'auto_number', prefix: 'D-' },
      { id: 'date', title: 'תאריך', type: 'date' },
      { id: 'weather', title: 'מזג אוויר', type: 'dropdown', labels: ['בהיר', 'גשם', 'חום קיצוני'] },
      { id: 'work_done', title: 'עבודות שבוצעו', type: 'long_text' },
      { id: 'issues', title: 'אירועים/עיכובים', type: 'long_text' },
      { id: 'photos', title: 'תמונות', type: 'file' },
      { id: 'photos_link', title: 'קישור תמונות Drive', type: 'link', description: 'נכתב ע״י M11a' },
      { id: 'ai_summary', title: 'סיכום AI', type: 'long_text', description: 'גל 3 (M20)' },
      { id: 'submitter', title: 'מגיש', type: 'people' },
      { id: 'project', title: 'פרויקט', type: 'relation', target: 'projects', single: true },
      { id: 'created', title: 'יומן יצירה', type: 'creation_log' },
      { id: 'int_key', title: 'מפתח אינטגרציה', type: 'text' },
    ],
    subitems: {
      nameTitle: 'קבלן / צוות',
      columns: [
        { id: 'subcontractor', title: 'קבלן משנה', type: 'relation', target: 'vendors', single: true },
        { id: 'workers', title: 'מספר עובדים', type: 'numbers' },
        { id: 'hours', title: 'שעות', type: 'numbers' },
      ],
    },
  },
  {
    key: 'defects', ws: 'w20', name: 'ליקויים ומסירה', kind: 'public', nameTitle: 'תיאור ליקוי',
    description: 'ליקוי. התראה לאחראי בתאריך היעד ולמנהל הביצוע יומיים אחריו. (אפיון §5.8)',
    groups: ['פתוחים', 'בתיקון', 'נסגרו'],
    columns: [
      { id: 'rec_id', title: 'מזהה', type: 'auto_number', prefix: 'DF-' },
      { id: 'severity', title: 'חומרה', type: 'status', labels: ['קריטי', 'גבוה', 'בינוני', 'נמוך'] },
      { id: 'status', title: 'סטטוס', type: 'status', labels: ['פתוח', 'בטיפול', 'תוקן', 'נבדק', 'נסגר'] },
      { id: 'location', title: 'מיקום', type: 'text' },
      { id: 'sub', title: 'קבלן אחראי', type: 'relation', target: 'vendors', single: true },
      { id: 'owner', title: 'אחראי', type: 'people' },
      { id: 'due', title: 'תאריך יעד', type: 'date' },
      { id: 'photo_before', title: 'תמונה לפני', type: 'file' },
      { id: 'photo_after', title: 'תמונה אחרי', type: 'file' },
      { id: 'project', title: 'פרויקט', type: 'relation', target: 'projects', single: true },
      { id: 'created', title: 'יומן יצירה', type: 'creation_log' },
      { id: 'int_key', title: 'מפתח אינטגרציה', type: 'text' },
    ],
  },
  {
    key: 'safety', ws: 'w20', name: 'בטיחות', kind: 'public', nameTitle: 'תיאור',
    description: 'רשומת בטיחות: הדרכה, סיור שבועי, ממצא, אירוע, הודעה נדרשת. תיקון התקנות בתוקף מ-16.10.2026. תוכנית הבטיחות החתומה ב-Drive/09. רשימת ההודעות תאושר מול יועץ הבטיחות. (אפיון §5.9)',
    groups: ['הדרכות', 'סיורים', 'ממצאים', 'אירועים', 'הודעות'],
    columns: [
      { id: 'rec_id', title: 'מזהה', type: 'auto_number', prefix: 'S-' },
      { id: 'rec_type', title: 'סוג', type: 'status', labels: ['הדרכה', 'סיור שבועי', 'ממצא', 'אירוע/כמעט אירוע', 'הודעה נדרשת'] },
      { id: 'date', title: 'תאריך', type: 'date' },
      { id: 'performer', title: 'מבצע', type: 'people' },
      { id: 'participants', title: 'משתתפים', type: 'numbers' },
      { id: 'severity', title: 'חומרה', type: 'status', labels: ['גבוהה', 'בינונית', 'נמוכה'] },
      { id: 'finding_status', title: 'סטטוס ממצא', type: 'status', labels: ['פתוח', 'בטיפול', 'נסגר', 'הוסלם'] },
      { id: 'close_due', title: 'מועד סגירה נדרש', type: 'date' },
      { id: 'close_overdue', title: 'חריגת סגירה', type: 'formula',
        formula: `IF(AND({finding_status}<>"נסגר",{close_due}<>""),IF(DAYS(${T},{close_due})>0,"באיחור",""),"")` },
      { id: 'notice_due', title: 'מועד אחרון להודעה', type: 'date' },
      { id: 'notice_ref', title: 'מספר אישור הודעה', type: 'text' },
      { id: 'training_log', title: 'קישור פנקס הדרכה', type: 'link' },
      { id: 'files', title: 'תמונות/מסמכים', type: 'file' },
      { id: 'project', title: 'פרויקט', type: 'relation', target: 'projects', single: true },
      { id: 'created', title: 'יומן יצירה', type: 'creation_log' },
      { id: 'int_key', title: 'מפתח אינטגרציה', type: 'text' },
    ],
  },

  // ───────────────────────────── 30 רכש וכספים (פרטי) ─────────────────────────────
  {
    key: 'budget', ws: 'w30', name: 'שורות תקציב', kind: 'private', nameTitle: 'שורת תקציב',
    description: 'פרויקט × קוד עלות (P26-014-22-SC). התחייבויות ושינויים מאושרים נכתבים ע״י M09a (סכום מלא, הרצה חוזרת לא מכפילה). עלות בפועל אינה מחושבת כאן. (אפיון §5.10)',
    groups: ['פרויקטים פעילים', 'פרויקטים סגורים'],
    columns: [
      { id: 'rec_id', title: 'מזהה', type: 'auto_number', prefix: 'B-' },
      { id: 'cost_code', title: 'קוד עלות מלא', type: 'text', description: 'P26-014-22-SC' },
      { id: 'chapter', title: 'פרק', type: 'dropdown',
        labels: ['00', '01', '02', '04', '05', '06', '07', '08', '09', '10', '11', '12', '14', '15', '18', '19', '22', '34'].map(chapter) },
      { id: 'cost_type', title: 'סוג עלות', type: 'dropdown', labels: ['SC', 'MT', 'LB', 'EQ', 'OH', 'IG', 'CO'] },
      { id: 'orig_budget', title: 'תקציב מקורי', type: 'numbers', description: 'ננעל אחרי התנעה (הגבלת עריכה לסמנכ״ל)' },
      { id: 'approved_changes', title: 'שינויים מאושרים', type: 'numbers', description: 'נכתב ע״י M09a' },
      { id: 'commitments', title: 'התחייבויות', type: 'numbers', description: 'נכתב ע״י M09a' },
      { id: 'revised', title: 'תקציב מעודכן', type: 'formula', formula: '{orig_budget}+{approved_changes}' },
      { id: 'remaining', title: 'יתרה להתחייבות', type: 'formula', formula: '{orig_budget}+{approved_changes}-{commitments}' },
      { id: 'utilization', title: 'ניצול %', type: 'formula',
        formula: 'IF(({orig_budget}+{approved_changes})=0,0,ROUND({commitments}/({orig_budget}+{approved_changes})*100,1))' },
      { id: 'budget_status', title: 'סטטוס תקציב', type: 'status', labels: ['תקין', 'מעל 90%', 'חריגה'], description: 'נכתב ע״י M09a' },
      { id: 'int_status', title: 'סטטוס אינטגרציה', type: 'status', labels: ['תקין', 'שגיאת אינטגרציה'] },
      { id: 'project', title: 'פרויקט', type: 'relation', target: 'projects', single: true },
      { id: 'created', title: 'יומן יצירה', type: 'creation_log' },
      { id: 'int_key', title: 'מפתח אינטגרציה', type: 'text' },
    ],
  },
  {
    key: 'orders', ws: 'w30', name: 'הזמנות רכש ועבודה', kind: 'private', nameTitle: 'תיאור הזמנה',
    description: 'הזמנה PO-26-0001. "מסלול אישור" נכתב ע״י M03. 3 הצעות נדרשות מעל 20,000 ש״ח ללא מחיר מסגרת. מאושר → M04 (PDF ושליחה). (אפיון §5.11)',
    groups: ['טיוטות', 'באישור', 'מאושרות', 'סגורות'],
    columns: [
      { id: 'rec_id', title: 'מזהה', type: 'auto_number', prefix: 'PO-' },
      { id: 'po_code', title: 'מזהה הזמנה', type: 'text', description: 'PO-26-0001' },
      { id: 'vendor', title: 'ספק', type: 'relation', target: 'vendors', single: true, reflect: 'הזמנות', reflectId: 'orders' },
      { id: 'budget_line', title: 'שורת תקציב', type: 'relation', target: 'budget', single: true, reflect: 'הזמנות', reflectId: 'orders' },
      { id: 'amount', title: 'סכום', type: 'numbers' },
      { id: 'in_budget', title: 'בתקציב', type: 'status', labels: ['כן', 'לא'] },
      { id: 'framework_price', title: 'מחיר מסגרת', type: 'checkbox' },
      { id: 'three_quotes', title: '3 הצעות צורפו', type: 'checkbox' },
      { id: 'approval_tier', title: 'דרג אישור', type: 'formula',
        formula: 'IF({in_budget}="כן",IF({amount}<=30000,"מנהל פרויקט",IF({amount}<=150000,"סמנכ״ל","מנכ״ל")),IF({amount}<=20000,"סמנכ״ל","מנכ״ל"))' },
      { id: 'approval', title: 'מסלול אישור', type: 'status',
        labels: ['טיוטה', 'ממתין מנהל פרויקט', 'ממתין סמנכ״ל', 'ממתין מנכ״ל', 'מאושר', 'נדחה', 'שגיאת אינטגרציה'],
        description: 'נכתב ע״י M03 — מקור הנתון לאוטומציות' },
      { id: 'status', title: 'סטטוס', type: 'status',
        labels: ['טיוטה', 'הוגש לאישור', 'ממתין מנהל פרויקט', 'ממתין סמנכ״ל', 'ממתין מנכ״ל', 'מאושר', 'נשלח לספק', 'סופק חלקית', 'הושלם', 'בוטל'] },
      { id: 'vendor_compliance', title: 'ציות ספק', type: 'mirror', relation: 'vendor', from: 'vendors', column: 'compliance' },
      { id: 'planned_delivery', title: 'אספקה מתוכננת', type: 'date' },
      { id: 'actual_delivery', title: 'אספקה בפועל', type: 'date' },
      { id: 'delivery_note', title: 'תעודת משלוח', type: 'link' },
      { id: 'pdf', title: 'PDF', type: 'link', description: 'נכתב ע״י M04' },
      { id: 'requester', title: 'מבקש', type: 'people' },
      { id: 'int_status', title: 'סטטוס אינטגרציה', type: 'status', labels: ['תקין', 'שגיאת אינטגרציה'] },
      { id: 'project', title: 'פרויקט', type: 'relation', target: 'projects', single: true },
      { id: 'created', title: 'יומן יצירה', type: 'creation_log' },
      { id: 'int_key', title: 'מפתח אינטגרציה', type: 'text' },
    ],
  },
  {
    key: 'vinvoices', ws: 'w30', name: 'חשבונות ספקים לאישור', kind: 'share', nameTitle: 'חשבונית',
    description: 'חשבונית ספק. מספר הקצאה חובה מעל 5,000 ש״ח לפני מע״מ. התשלום עצמו מתבצע בבנק בהרכב חתימות כפול — כאן נרשמים האישורים בלבד. הנהלת החשבונות כאורחת (צפייה ותגובה). (אפיון §5.12)',
    groups: ['נקלטו', 'באישור', 'מוכן לתשלום', 'שולם'],
    columns: [
      { id: 'rec_id', title: 'מזהה', type: 'auto_number', prefix: 'VI-' },
      { id: 'vendor', title: 'ספק', type: 'relation', target: 'vendors', single: true },
      { id: 'po', title: 'הזמנה', type: 'relation', target: 'orders', single: true, reflect: 'חשבוניות ספק', reflectId: 'vinvoices' },
      { id: 'invoice_no', title: 'מספר חשבונית', type: 'text' },
      { id: 'net_amount', title: 'סכום לפני מע״מ', type: 'numbers' },
      { id: 'allocation_no', title: 'מספר הקצאה', type: 'text' },
      { id: 'alloc_required', title: 'דרוש מספר הקצאה', type: 'formula',
        formula: 'IF(AND({net_amount}>5000,{allocation_no}=""),"חסר","")' },
      { id: 'three_way', title: 'התאמה משולשת', type: 'status',
        labels: ['לא נבדק', 'תואם', 'פער כמות', 'פער מחיר', 'ללא הזמנה', 'ללא מספר הקצאה'] },
      { id: 'cum_approved', title: 'מצטבר מאושר', type: 'numbers' },
      { id: 'retention', title: 'עיכבון', type: 'numbers' },
      { id: 'to_pay', title: 'סכום לתשלום', type: 'numbers' },
      { id: 'pay_approval', title: 'אישור תשלום', type: 'status', labels: ['ממתין', 'אושר', 'נדחה', 'דרוש תיקון'] },
      { id: 'second_approval', title: 'אישור שני', type: 'status', labels: ['לא נדרש', 'ממתין', 'אושר'], description: 'נדרש מעל 50,000 ש״ח' },
      { id: 'vendor_block', title: 'חסימת תשלום', type: 'mirror', relation: 'vendor', from: 'vendors', column: 'pay_block',
        description: 'מראה מהספק. M03 קורא את העמודה המקורית בספק, לא את המראה.' },
      { id: 'ready', title: 'מוכן לתשלום', type: 'formula',
        formula: 'IF(AND({three_way}="תואם",{pay_approval}="אושר",OR({to_pay}<=50000,{second_approval}="אושר"),OR({net_amount}<=5000,{allocation_no}<>"")),"מוכן","לא")' },
      { id: 'paid_date', title: 'בוצע בבנק', type: 'date' },
      { id: 'paid_by', title: 'מבצע התשלום', type: 'people' },
      { id: 'file', title: 'קובץ', type: 'link' },
      { id: 'int_status', title: 'סטטוס אינטגרציה', type: 'status', labels: ['תקין', 'שגיאת אינטגרציה'] },
      { id: 'project', title: 'פרויקט', type: 'relation', target: 'projects', single: true },
      { id: 'created', title: 'יומן יצירה', type: 'creation_log' },
      { id: 'int_key', title: 'מפתח אינטגרציה', type: 'text' },
    ],
  },
  {
    key: 'billing', ws: 'w30', name: 'חשבונות חלקיים וגבייה', kind: 'private', nameTitle: 'חשבון',
    description: 'חשבון חלקי BL-26-014-05. אושר → M06a (חשבון עסקה ב-Morning). תשלום → M06b (חשבונית מס-קבלה + מספר הקצאה). סולם גבייה A10. מע״מ 18% — לאמת. (אפיון §5.13)',
    groups: ['בהכנה', 'אצל מפקח', 'הופק', 'נגבה'],
    columns: [
      { id: 'rec_id', title: 'מזהה', type: 'auto_number', prefix: 'BL-' },
      { id: 'bill_code', title: 'מזהה חשבון', type: 'text', description: 'BL-26-014-05' },
      { id: 'bill_status', title: 'סטטוס חיוב', type: 'status',
        labels: ['בהכנה', 'הוגש למפקח', 'הערות מפקח', 'אושר', 'הופק מסמך', 'שולם חלקית', 'שולם'] },
      { id: 'cum_qty', title: 'כמויות מצטבר', type: 'numbers', description: 'מגיליון המדידה המצטברת' },
      { id: 'cum_changes', title: 'שינויים מצטבר', type: 'numbers' },
      { id: 'prev_bills', title: 'חשבונות קודמים', type: 'numbers' },
      { id: 'retention_pct', title: 'עיכבון %', type: 'numbers' },
      { id: 'to_bill', title: 'לחיוב', type: 'formula',
        formula: 'ROUND(({cum_qty}+{cum_changes})*(1-{retention_pct}/100)-{prev_bills},0)' },
      { id: 'submitted', title: 'תאריך הגשה', type: 'date' },
      { id: 'approved_amt', title: 'מאושר מפקח', type: 'numbers' },
      { id: 'approved_date', title: 'תאריך אישור מפקח', type: 'date' },
      { id: 'days_to_approve', title: 'ימים לאישור מפקח', type: 'formula',
        formula: 'IF(OR({approved_date}="",{submitted}=""),"",DAYS({approved_date},{submitted}))' },
      { id: 'doc_type', title: 'סוג מסמך', type: 'status', labels: ['חשבון עסקה', 'חשבונית מס', 'חשבונית מס-קבלה'] },
      { id: 'doc_no', title: 'מספר מסמך', type: 'text', description: 'נכתב ע״י M06a/M06b' },
      { id: 'allocation_no', title: 'מספר הקצאה', type: 'text', description: 'נכתב ע״י M06b' },
      { id: 'pdf', title: 'PDF', type: 'link' },
      { id: 'due', title: 'מועד פירעון', type: 'date' },
      { id: 'paid', title: 'שולם', type: 'numbers' },
      { id: 'balance', title: 'יתרה', type: 'formula', formula: 'ROUND({approved_amt}*1.18-{paid},0)',
        description: 'כולל מע״מ 18% — לעדכן אם השיעור משתנה' },
      { id: 'days_late', title: 'ימי איחור', type: 'formula',
        formula: `IF(OR(ROUND({approved_amt}*1.18-{paid},0)<=0,{due}=""),0,MAX(DAYS(${T},{due}),0))` },
      { id: 'collection', title: 'שלב גבייה', type: 'status',
        labels: ['בזמן', '7 תזכורת', '14 שיחת PM', '21 שיחת סמנכ״ל', '30 מכתב מנכ״ל', '45 עו״ד'], description: 'נכתב ע״י M08' },
      { id: 'int_status', title: 'סטטוס אינטגרציה', type: 'status', labels: ['תקין', 'שגיאת אינטגרציה'] },
      { id: 'project', title: 'פרויקט', type: 'relation', target: 'projects', single: true },
      { id: 'created', title: 'יומן יצירה', type: 'creation_log' },
      { id: 'int_key', title: 'מפתח אינטגרציה', type: 'text' },
    ],
  },
  {
    key: 'guarantees', ws: 'w30', name: 'ערבויות וביטוחים', kind: 'private', nameTitle: 'ערבות / פוליסה',
    description: 'ערבות או פוליסה ספציפית לפרויקט. 30 ימים לפני תוקף — הודעה לסמנכ״ל. בסגירת פרויקט — משימת השבה (M14). (אפיון §5.14)',
    groups: ['בתוקף', 'לחידוש', 'הושבו'],
    columns: [
      { id: 'rec_id', title: 'מזהה', type: 'auto_number', prefix: 'G-' },
      { id: 'g_type', title: 'סוג', type: 'status', labels: ['ערבות ביצוע', 'ערבות בדק', 'ערבות מקדמה', 'אישור ביטוח פרויקט'] },
      { id: 'amount', title: 'סכום', type: 'numbers' },
      { id: 'issuer', title: 'מוטב/מנפיק', type: 'text' },
      { id: 'expiry', title: 'תוקף', type: 'date' },
      { id: 'file', title: 'קובץ', type: 'link' },
      { id: 'status', title: 'סטטוס', type: 'status', labels: ['בתוקף', 'לחידוש', 'הושב'] },
      { id: 'project', title: 'פרויקט', type: 'relation', target: 'projects', single: true },
      { id: 'created', title: 'יומן יצירה', type: 'creation_log' },
      { id: 'int_key', title: 'מפתח אינטגרציה', type: 'text' },
    ],
  },

  // ───────────────────────────── 50 הנהלה ─────────────────────────────
  {
    key: 'tasks', ws: 'w50', name: 'משימות ותפעול שוטף', kind: 'public', nameTitle: 'משימה',
    description: 'משימה שאין לה לוח תהליך. נקודות כניסה: טופס "בקשה למשרד", דוא״ל ללוח, החלטות מפגישה, שגרות (A12). פריטי תהליך נשארים בלוח שלהם. ארכוב "הושלם" ברבעון. (אפיון §5.15, §7)',
    groups: ['השבוע', 'בהמשך', 'שגרות', 'הושלם'],
    columns: TASK_COLUMNS,
  },
  {
    key: 'renewals', ws: 'w50', name: 'חידושים ונכסים', kind: 'public', nameTitle: 'פריט',
    description: 'מרשם קבוע (לא משימה): פוליסות, רשם הקבלנים, רכבים, שכירות, מנויים, דומיין, מסגרות בנק, הסמכות. A14: משימה 60 יום לפני. A15: תזכורת 14 יום לפני. ערבויות לפרויקט — בלוח ערבויות. (אפיון §5.16)',
    groups: ['ביטוח', 'רישוי', 'רכבים', 'משרד', 'תוכנה ודומיין', 'בנק', 'הסמכות'],
    columns: [
      { id: 'rec_id', title: 'מזהה', type: 'auto_number', prefix: 'R-' },
      { id: 'r_type', title: 'סוג', type: 'dropdown',
        labels: ['פוליסה', 'רשם הקבלנים', 'רכב-רישיון', 'רכב-ביטוח', 'רכב-טסט', 'ליסינג', 'שכירות', 'מנוי תוכנה', 'דומיין/אתר', 'מסגרת בנקאית', 'הסמכת עובד', 'ISO'] },
      { id: 'counterparty', title: 'צד נגדי', type: 'text' },
      { id: 'expiry', title: 'תאריך תוקף', type: 'date' },
      { id: 'annual_cost', title: 'עלות שנתית', type: 'numbers' },
      { id: 'owner', title: 'אחראי', type: 'people' },
      { id: 'renewal_status', title: 'סטטוס חידוש', type: 'status', labels: ['בתוקף', 'בתהליך', 'חודש', 'לא לחדש'] },
      { id: 'drive', title: 'קישור Drive', type: 'link' },
      { id: 'created', title: 'יומן יצירה', type: 'creation_log' },
      { id: 'int_key', title: 'מפתח אינטגרציה', type: 'text' },
    ],
  },
  {
    key: 'sensitive', ws: 'w50', name: 'משימות רגישות', kind: 'private', nameTitle: 'משימה',
    description: 'לוח פרטי למנכ״ל ולסמנכ״ל בלבד: שכר, משאבי אנוש ועניינים אישיים. מבנה זהה למשימות, ללא אוטומציות חיצוניות. (ב-Pro אין הסתרת פריט בודד.) (אפיון §5.17)',
    groups: ['פתוחות', 'הושלמו'],
    columns: TASK_COLUMNS.map((c) => (c.id === 'rec_id' ? { ...c, prefix: 'ST-' } : c)),
  },
  {
    key: 'snapshot', ws: 'w50', name: 'תמונת מצב חודשית ותזרים', kind: 'private', nameTitle: 'חודש',
    description: 'פריט = חודש (למשל 2026-10). נכתב ע״י M13 ו-M18. משמש את מסך המנכ״ל. (אפיון §5.18)',
    groups: ['2026', '2027'],
    columns: [
      { id: 'rec_id', title: 'מזהה', type: 'auto_number', prefix: 'M-' },
      { id: 'low_balance', title: 'יתרה נמוכה צפויה', type: 'numbers' },
      { id: 'deficit_weeks', title: 'שבועות בגירעון', type: 'numbers' },
      { id: 'first_deficit', title: 'שבוע ראשון בגירעון', type: 'date' },
      { id: 'backlog', title: 'צבר', type: 'numbers' },
      { id: 'portfolio_margin', title: 'רווחיות פורטפוליו %', type: 'numbers' },
      { id: 'dso', title: 'ימי גבייה', type: 'numbers' },
      { id: 'quote_cycle', title: 'זמן מחזור הצעה (ימים)', type: 'numbers' },
      { id: 'on_time_pct', title: 'מסירה בזמן %', type: 'numbers' },
      { id: 'created', title: 'יומן יצירה', type: 'creation_log' },
      { id: 'int_key', title: 'מפתח אינטגרציה', type: 'text' },
    ],
  },
  {
    key: 'intlog', ws: 'w50', name: 'יומן אינטגרציות', kind: 'private', nameTitle: 'הרצה',
    description: 'הרצה או שגיאה של תרחיש Make. כשלים נרשמים תמיד; הצלחות כסיכום יומי, למעט תרחישים כספיים (M03, M04, M06, M09a). שמירה 90 יום. תצוגה מומלצת: "נכשל ולא טופל". (אפיון §5.19, §8.7)',
    groups: ['נכשל', 'הצליח (סיכום יומי)', 'טופל'],
    columns: [
      { id: 'rec_id', title: 'מזהה', type: 'auto_number', prefix: 'LOG-' },
      { id: 'scenario', title: 'תרחיש', type: 'dropdown',
        labels: ['M01', 'M02', 'M03', 'M04', 'M04w', 'M05a', 'M05b', 'M06a', 'M06b', 'M07', 'M08', 'M09a', 'M09b', 'M10', 'M11a', 'M11b', 'M12', 'M13', 'M14', 'M16', 'M17', 'M18', 'M19', 'M19b', 'M20', 'M21', 'M22'] },
      { id: 'version', title: 'גרסה', type: 'text' },
      { id: 'result', title: 'תוצאה', type: 'status', labels: ['הצליח', 'דולג', 'נכשל', 'הוסלם'] },
      { id: 'source_board', title: 'לוח מקור', type: 'text' },
      { id: 'source_item', title: 'מזהה פריט מקור', type: 'text' },
      { id: 'int_key', title: 'מפתח אינטגרציה', type: 'text' },
      { id: 'run_time', title: 'זמן', type: 'date' },
      { id: 'error', title: 'שגיאה', type: 'long_text' },
      { id: 'handled', title: 'טופל', type: 'checkbox' },
      { id: 'handler', title: 'מטפל', type: 'people' },
      { id: 'created', title: 'יומן יצירה', type: 'creation_log' },
    ],
  },
];

// ───────────────────── צבעי סטטוס ─────────────────────
// מזהה התווית ב-monday נגזר מהצבע, לכן בכל עמודה כל תווית מקבלת צבע שונה.
const GREEN = ['הושלם', 'נסגר', 'שולם', 'מאושר', 'אושר', 'תקין', 'בתוקף', 'חודש', 'תואם', 'הצליח', 'זכייה', 'בוצע', 'כן', 'מאומת', 'תוקן', 'הושב', 'בזמן', 'חויב', 'לקוח', 'ליד'];
const DARK_GREEN = ['חוזה נחתם', 'נבדק', 'נגבה', 'הופק מסמך', 'נשלח לספק'];
const ORANGE = ['בטיפול', 'בתהליך', 'בתמחור', 'ממתין', 'ממתין לאימות', 'הוגש', 'הוגש לאישור', 'הוגש למפקח', 'ממתין סמנכ״ל', 'פג בעוד 30', 'מעל 90%', 'בינוני', 'בינונית', 'סופק חלקית', 'שולם חלקית', 'לחידוש', '7 תזכורת', 'גבוה'];
const RED = ['חריגה', 'נדחה', 'פג תוקף', 'נכשל', 'הוסלם', 'בוצע ללא אישור', 'הפסד', 'קריטי', 'דחוף', 'שגיאת אינטגרציה', 'חסר', 'שונה', '45 עו״ד', 'גבוהה', 'ממתין מנכ״ל', 'פג בעוד 7', 'פער מחיר', 'פער כמות', 'ללא מספר הקצאה', 'ללא הזמנה', 'פתוח', 'לא', 'ממתין להחלטה', 'דרוש תיקון', 'הערות מפקח'];
const GRAY = ['טיוטה', 'לא נבדק', 'לא הוגש', 'ללא', 'טרם', 'לא נדרש', 'לא מתאים', 'בוטל', 'מוקפא', 'סגור', 'לא בוצע', 'לא לחדש', 'נמוך', 'נמוכה', 'דולג', 'בהכנה', 'פוטנציאלי', 'חדש', 'ליד חדש'];
const PALETTE = ['bright_blue', 'purple', 'dark_blue', 'saladish', 'egg_yolk', 'sofia_pink', 'chili_blue', 'dark_purple', 'brown', 'lipstick', 'dark_orange', 'bright_green', 'blackish', 'dark_red', 'grass_green', 'explosive', 'american_gray', 'done_green', 'working_orange', 'stuck_red'];
export const DONE_LABELS = new Set(['הושלם', 'נסגר', 'שולם', 'הושב', 'נגבה', 'חוזה נחתם', 'טופל']);

export function statusColors(labels) {
  const used = new Set();
  const pick = (preferred) => {
    for (const c of preferred) if (!used.has(c)) { used.add(c); return c; }
    for (const c of PALETTE) if (!used.has(c)) { used.add(c); return c; }
    throw new Error('out of colors');
  };
  return labels.map((label) => {
    if (GREEN.includes(label)) return pick(['done_green', 'grass_green', 'bright_green', 'saladish']);
    if (DARK_GREEN.includes(label)) return pick(['grass_green', 'bright_green', 'saladish', 'done_green']);
    if (ORANGE.includes(label)) return pick(['working_orange', 'egg_yolk', 'dark_orange']);
    if (RED.includes(label)) return pick(['stuck_red', 'dark_red', 'lipstick', 'sofia_pink']);
    if (GRAY.includes(label)) return pick(['american_gray', 'explosive', 'blackish']);
    return pick(PALETTE);
  });
}
